### PR TITLE
#29 Fixes first item active issue if multiple tab or accordion elements occur on the same page

### PR DESCRIPTION
**Pull request by maechler**
See https://github.com/laxap/bootstrap_grids/issues/29

### CODE REVIEW

**Comment by Moongazer** [comment]
The provided commit solves the issue (tested with 2 SimpleTab elements on one page)

**Comment by maechler** [comment]
@Moongazer Thanks!

**Comment by maechler** [comment]
@laxap Is this extension still being maintained?

**Comment by maechler** [comment]
@laxap Thanks! 🎉

**Pull request merged**
